steps <- data.frame(name = c("do 1.1", "do 2.1", "do 3"), from = c("1", "2", "1.1, 2.1"), to = c("1.1", "2.1", "3"))
steps
nodes <- workflowchart(indat = steps, names_col = "name", in_col = "from", out_col = "to", sideways = F)
                       #, clusters_col = "CLUSTER", todo_col="STATUS")

DiagrammeR::grViz(nodes)

tmp <- DiagrammeR::grViz(diagram = nodes)
# 2. Convert to SVG, then save as png
tmp <- DiagrammeRsvg::export_svg(tmp)
tmp <- charToRaw(tmp) # flatten
rsvg::rsvg_png(tmp, sprintf("inst/%s.png", "workflowchart_demo")) # saved graph as png in current working directory


nodes <- workflowchart(indat = steps, names_col = "name", in_col = "from", out_col = "to", sideways = T)
                       #, clusters_col = "CLUSTER", todo_col="STATUS")

DiagrammeR::grViz(nodes)

tmp <- DiagrammeR::grViz(diagram = nodes)
# 2. Convert to SVG, then save as png
tmp <- DiagrammeRsvg::export_svg(tmp)
tmp <- charToRaw(tmp) # flatten
rsvg::rsvg_png(tmp, sprintf("inst/%s.png", "workflowchart_demo_sideways")) # saved graph as png in current working directory


